// Foranes and parishes of the Archdiocese of Changanacherry, from
// https://www.archdiocesechanganacherry.org/welcome/forane_list (fetched 29 Sep 2026).
// Parish names are "Church, Place" because many churches share a name.

export const ARCHDIOCESE = 'Archdiocese of Changanacherry';

export const PARISHES_BY_FORANE = {
  "Alappuzha": [
    "Immaculate Heart Church, Kaithavana",
    "Little Flower Church, Aryad",
    "Mar Gregorios Church, Punnapra",
    "Mar Sleeva Church, Purakkadu",
    "Mar Sleeva Forane Pilgrim Church, Alappuzha",
    "Sacred Heart Church, Arunoottampadam",
    "St. Alphonsa Church, Chathanad",
    "St. Francis Assissi Church, Poonthope",
    "St. George Catholic Church, Puthenangady (Chakkarakadavu)",
    "St. Joseph's Church, Arattuvazhy",
    "St. Joseph's Church, Kuttamangalam",
    "St. Mary's Church, Kainakary",
    "St. Mary's Church, Punnamada",
    "St. Michael's Church, Thathampally",
    "St. Thomas Church, Pallathuruthy",
  ],
  "Amboory": [
    "Christ the King Church, Rajagiri",
    "Sacred Heart Church, Pachakadu (Dalumugham)",
    "Sacred Heart Church, Vavode",
    "St. Alphonsa Church, Changanacherry",
    "St. George's Forane Church, Amboori",
    "St. Joseph's Church, Kuchapuram",
    "St. Mary's Church, Dalumugham",
    "St. Mary's Church, Mayam",
    "St. Mary's Church, Thekkupara",
  ],
  "Athirambuzha": [
    "Christuraj Church, Ettumanoor",
    "Lisieux Church, Athirampuzha (Sreekandamangalam)",
    "Mangalavartha Church, Arumanoor",
    "St. Gregorios Church, Mannarkunnu",
    "St. Joseph's Church, Thellakom-Pushpagiri",
    "St. Mary's Church, Vettimukal",
    "St. Mary's Forane Church, Athirampuzha",
    "St. Mathew's Church, Kottackupuram",
    "St. Sebastian's Church, Cheruvandoor",
    "St. Thomas Church, Nalpathimala",
    "St. Thomas Church, Pallikkunnu",
    "St. Thomas Church, Punnathura",
    "St. Xavier's Church, Kattachira",
    "Twelve Apostles Church, Mannanam",
  ],
  "Champakulam": [
    "Holy Family Church, Pullangady",
    "Lourdes Matha Church, Chennamkary (Koolippurackal)",
    "Mar Sleeva Church, Ponga",
    "Sacred Heart Church, Thottuvathala",
    "St. Antony's Church, Vaisyambhagom (Paduvapuram)",
    "St. George Church, Vadakke Amichakary",
    "St. Jerome Church, Nazareth",
    "St. John's Church, Thekkekara",
    "St. Joseph's Church, Chennamkary West",
    "St. Joseph's Church, Kandankary",
    "St. Joseph's Church, Kondackal",
    "St. Joseph's Church, Padaharam",
    "St. Mary's Basilica, Champakulam-Kalloorkad",
    "St. Sebastian's Church, Narbonapuram",
    "St. Sebastian's Church, Thekkekara East",
  ],
  "Changanacherry": [
    "Marth Mariyam Church, Kunnamkary-Pulimugham",
    "Sacred Heart Church, Chethipuzha",
    "St. Antony's Church, Paral",
    "St. Antony's Church, Perunna",
    "St. Antony's Filial Church, Vettithuruthu",
    "St. George Church, Cheeranchira",
    "St. Gregorios Church, Kidangara",
    "St. Joseph's Church, Laikadu",
    "St. Joseph's Church, Manackachira",
    "St. Joseph's Church, Veroor",
    "St. Mary's Church, Kumarankary",
    "St. Mary's Church, Parel",
    "St. Mary's Church, Vazhappally West (Parekadavu)",
    "St. Mary's Metropolitan Church, Changanacherry",
    "St. Sebastian's Church, Mahendrapuram",
    "St. Thomas Church, Puzhavathu",
  ],
  "Chenganoor": [
    "Lourdes Matha Church, Ayroor",
    "Lourdes Matha Church, Puthusserry-Kalloopara",
    "Mar Sleeva Church, Adoor",
    "Marth Mariam Forane Church, Chengannur",
    "St. Alphonsa's Church, Mavelikara",
    "St. Antony's Church, Thadiyoor",
    "St. Joseph's Church, Ezhumattoor",
    "St. Mary's Church, Nedumon",
  ],
  "Edathua": [
    "Fathima Matha Church, Pandy",
    "Holy Family Church, Kariyil",
    "Holy Family Church, Kizhakke Mithrakary",
    "Immaculate Conception Church (Koventha Pally), Muttar",
    "Lourdes Matha Church, Pacha-Chekkidikad",
    "Mar Thoma Sleeha Pilgrim Centre, Niranam",
    "Mary Matha Church, Mariyapuram",
    "Our Lady of Dolours Church, Kelamangalam",
    "St. Antony's Church, Thayamkary",
    "St. George Forane Church, Edathua-Koilmuck",
    "St. George's Church, Muttar Old",
    "St. Joseph's Church, Changankary",
    "St. Joseph's Church, Karumady",
    "St. Joseph's Church, Karuvatta",
    "St. Joseph's Church, Koduppunna",
    "St. Joseph's Church, Koilmuck",
    "St. Jude's Church, Viruppala (Thakazhy)",
    "St. Mary's Church, Ambalapuzha",
    "St. Mary's Church, Kumarapuram (Karuvatta)",
    "St. Nicholas' Church, Karumady",
    "St. Pius X Church, Pandankary",
    "St. Rita's Church, Thakazhy-Thennady",
    "St. Thomas Church, Muttar New",
    "St. Xavier's Church, Puthukary",
  ],
  "Kollam-Ayoor": [
    "Christ the King Church, Kuttikonam",
    "Christ the King Forane Church, Ayoor",
    "Infant Jesus Church, Cherukadavu",
    "Lourdes Matha Church, Meenkulam",
    "Mar Aprem Mission Church, Pathanapuram",
    "Mary Matha Church, Anchal",
    "Nithya Sahaya Matha Church, Karavaloor",
    "Nithyasahaya Matha Church, Chenkulam",
    "Sacred Heart Church, Punaloor",
    "St. George's Church, Edapalayam",
    "St. George's Church, Venchempu",
    "St. Joseph's Church, Anakulam",
    "St. Joseph's Church, Philigiri",
    "St. Mary's Church, Aryankavu",
    "St. Mary's Church, Narikkal",
    "St. Sebastian's Church, Cheriyavelinalloor",
    "St. Sebastian's Church, Kulathupuzha",
    "St. Thomas Church, Pazhayeroor",
    "St. Thomas Syro Malabar Catholic Church, Kottarakkara",
    "Thoma Sleeha Pally, Kollam",
  ],
  "Kottayam": [
    "Assumption Church, Eravinalloor",
    "Deivamatha Church, Pampady",
    "Little Flower Church, Kollad (Kaduvakulam)",
    "Lourdes Forane Church, Kottayam",
    "Lourdes Matha Church, Aruvikuzhy",
    "Mar Sleeva Church, Kooroppada",
    "Marth Mariam Church, Cheppumpara",
    "Sacred Heart Church, Pangada",
    "Sacred Heart Church, Thazhathangady",
    "St. Antony's Church, Puthuppally-Poomattom",
    "St. Sebastian's Church, Ayarkunnam",
    "St. Thomas Church, Vadavathoor",
  ],
  "Kudamaloor": [
    "Bethlehem Church, Parampuzha",
    "Holy Family Church, Kaipuzha",
    "Holy Family Church, Mudiyoorkara",
    "Little Flower Church, Arpookara",
    "Nava Nazareth Church (Holy Family), Kumarakom",
    "St. Mary's Major Archiepiscopal Pilgrim Centre, Kudamaloor",
    "St. Antony's Church, Cheeppunkal",
    "St. Francis De Sales Church, Kiliroor",
    "St. George's Church, Aikkarachira",
    "St. John Nepumseanos Church, Kumarakom-Vadakumkara",
    "St. Joseph's Church, Mannanam",
    "St. Sebastian's Church, Chengalam",
    "St. Thomas Church, Kumaranalloor",
    "St. Xavier's Church, Arpookara-Villoonni",
  ],
  "Kurumpanadam": [
    "Assumption Church, Kurumpanadom",
    "Holy Family Church, Mannila",
    "Little Flower Church, Madappally",
    "Lourdes Matha Church, Mammood",
    "Sacred Heart Church, Rajamattom",
    "St. Antony's Forane Church, Kurumpanadom",
    "St. George's Church, Thottackad",
    "St. Mary's Church, Eravuchira",
  ],
  "Manimala": [
    "Holy Magi Forane Church, Manimala",
    "Little Flower Church, Chunkappara",
    "Little Flower Church, Kulathoor",
    "Sacred Heart Church, Karimpanakulam",
    "St. Basil's Church, Manimala New",
    "St. James Church, Karikkattoor",
    "St. John the Baptist Church, Kottangal",
    "St. Mary's Church, Kadayanickadu",
    "St. Mary's Church, Nirmalapuram",
    "St. Mary's Church, Vallamchira",
    "St. Thomas Church, Perumkavu",
  ],
  "Muhamma": [
    "Lourdes Matha Church, Charamangalam",
    "St. Antony's Church, Paduvapuram",
    "St. George's Forane Church, Muhamma",
    "St. Mary's Church, Mannancherry",
    "St. Sebastian's Church, SL Puram",
    "St. Thomas Church, Kalavoor",
  ],
  "Nedumkunnam": [
    "Fathima Matha Church, Nedumanny",
    "Little Flower Church, Punnavely",
    "Lourdes Matha Church, Thazhathuvadakara",
    "St. Antony's Church, Anicadu",
    "St. Antony's Church, Mundathanam",
    "St. Athanasius Church, Mallappally (Nedungadappally)",
    "St. John the Baptist Forane Church, Nedumkunnam",
    "St. Joseph's Church, Champakara",
    "St. Joseph's Church, Vaipur New",
    "St. Mary's Church, Koothrappally",
    "St. Mary's Church, Pulickalkavala",
    "St. Mary's Church, Vaipur Old",
    "St. Sebastian's Church, Panayampala",
    "St. Sebastian's Church, Vettickalpurayidom",
  ],
  "Pulincunnoo": [
    "Fathima Matha Church, Pallikkoottumma",
    "Lisieux Little Flower Church, Kavalam",
    "Lourdes Matha Church, Mampuzhakary",
    "St. Antony's Church, Kayalpuram",
    "St. Gregory's Church, Veliyanadu North (Kesaria)",
    "St. Joseph's Church, Kannady",
    "St. Joseph's Church, Kayalpuram",
    "St. Joseph's Church, Punnakkunnathussery",
    "St. Joseph's Church, Ramankary",
    "St. Joseph's Church, Veliyanadu (North)",
    "St. Mary's Church, Manalady",
    "St. Mary's Forane Church, Pulincunnoo",
    "St. Paul's Church, Vezhapra",
    "St. Pius X Church, Moncompu",
    "St. Rita's Church, Kannady",
    "St. Theresa's Church, Kavalam",
    "St. Xavier's Church, Mithrakary",
    "St. Xavier's Church, Veliyanadu (South)",
  ],
  "Thiruvananthapuram": [
    "All Saints Church, Vithura",
    "Holy Family Church, Thirumala",
    "Little Flower Church, Vellayani",
    "Lourdes Forane Church, Thiruvananthapuram",
    "Lourdes Hill Church, Peroorkada",
    "Mar Geevarghese Sahada Church, Kesavadasapuram",
    "Ranigiri Church, Mannanthala",
    "Sacred Heart Church, Thiruvallam-Kovalam",
    "St. Alphonsa Church, Pongummoodu",
    "St. Francis De Sales Church, Vattiyoorkavu",
    "St. John Paul II Church, Killy",
    "St. Joseph's Church, Karyavattom",
    "St. Joseph's Church, Sreekaryam-Emmaus",
    "St. Jude's Church, Attingal",
    "St. Mary's Church, Palode",
    "St. Mother Teresa Church, Kannammoola",
    "St. Peter's Church, Vizhinjam",
  ],
  "Thrickodithanam": [
    "Fathima Matha Church, Fathimapuram",
    "Lourdes Matha Church, Paippadu",
    "St. Antony's Church, Thiruvalla-Muthoor",
    "St. Joseph's Church, Kunnamthanam",
    "St. Mary's Church, Mundupalam",
    "St. Sebastian's Church, Chanjody",
    "St. Sebastian's Church, Kodinattumkunnu",
    "St. Thomas Church, Nalukody-Paippad",
    "St. Xavier's Forane Church, Thrickodithanam",
  ],
  "Thuruthy": [
    "Holy Family Church, Payattupakka",
    "Holy Family Church, Podippara",
    "Lourdes Matha Church, Eara",
    "Marth Mariam Forane Church, Thuruthy",
    "Our Lady of Dolours Church, Kainady",
    "St. Joseph's Church, Kavalam",
    "St. Joseph's Church, Kurichy (Santhigiri)",
    "St. Jude's Church, Yudapuram",
    "St. Mary's Church, Ithithanam",
    "St. Mary's Church, Vadakkekara",
  ],
};

export const FORANES = Object.keys(PARISHES_BY_FORANE);
